name: black

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Black Code Formatter
        uses: lgeiger/black-action@master
        with:
          args: ". --check"
        working-directory: ~/
        run: ls
